### PR TITLE
170   allow run cpm to be used as a GitHub action for submit jobs

### PR DESCRIPTION
**Pull request by ravn**

### CODE REVIEW

**Comment by ravn** [comment]
Accidentially opened.  My bad.

**Comment by MockbaTheBorg** [comment]
@ravn Please check my last two commits. I think setting Lua as a submodule made the build processes fail.

**Comment by ravn** [comment]
@MockbaTheBorg  What would you like me to do?

**Comment by ravn** [comment]
@MockbaTheBorg You may want to use the opportunity to consider removing Lua completely, or just make the default to be non-present with instructions on how to enable it (change a setting and tell git to get submodules).  I know this is dear to you, but if it is not actually used for anything it just complicates stuff.

**Comment by MockbaTheBorg** [comment]
This is actually a good point. Make Lua completely optional. To the point it won't build by default.

**Pull request closed without merging**
