### PR TITLE
Makefiles cleaned up, added simple configure script

### PR DESCRIPTION
**Pull request by kklis**
Tested on MSYS32, Ubuntu 16.04, Mac OS X El Capitan, FreeBSD 10.3. I didn't want to use all the complicated autoconf machine to build a humongous Makefile, so just made a simple system auto detection.

### CODE REVIEW

**Comment by kklis** [comment]
I left make.bat untouched as it still makes RunCPM buildable under TDM-GCC in Windows.

**Comment by MockbaTheBorg** [comment]
Last night I tried to build on my msys64 and was able to see the error
messages. It complains that I am redefining _fopen_r, so it seems that it
is already defined by the system before that.
It also won't find ncurses.h even though I have ncurses-devel installed.
So, I have a feeling that the problem is only because of dependencies.
I am driving back home today, so tomorrow I may be able to fix it.

**Comment by kklis** [comment]
Unfortunately I don't have access to Win64 so I'm not able to test it with msys64. Meanwhile, I verified that it builds fine under Microsoft Visual Express 2005 :)

**Comment by MockbaTheBorg** [comment]
Yeah, I will try to figure this out. It must be some dependency issue
between msys64 and msys32.

**Pull request merged**
