### PR TITLE
[WIP] Implement iobyte for TTY

### PR DESCRIPTION
**Pull request by TurBoss**
Implement iobyte from moxhamj's issue #85 code

Ive been testing it on a teensy 4.1
going to give a try on a esp32

did a pull request allow easy test this to others and allow reviews

Thanks!

### CODE REVIEW

**Comment by MockbaTheBorg** [comment]
Cool.

Thanks for taking the time to do this.
I had it in mind but the pandemic killed it.
Let's hold on to the pull request until you have tested in the ESP32.
Would be perfect if you could also add some Due corresponding code and some
skeleton we could leave in place for the other platforms, like vstudio and
posix.

Thanks a lot.

**Comment by TurBoss** [comment]
Hello!

Got the esp32s3 i have to work!

```
RunCPM Version 6.3 (CP/M 60K)

A0>kermit
Kermit-80 v4.11 configured for Generic CP/M-80 with Generic (Dumb) CRT Terminal type selected 

For help, type ? at any point in a command
Kermit-80   0A:>SET PORT TTY
Kermit-80   0A:>SET TERMINAL OFF
Kermit-80   0A:>c
[Connected to remote host.  Type Control-\C to return;
 type Control-\? for command list]
ATI

Zimodem ESP32 Firmware v4.0.1
sdk=v4.4.6-dirty chipid=0 cpu@240
tot=8192k heap=268k fsize=1287k
CONNECTED TO TP-LINK (192.168.10.136)
READY.
OK
```

But i have to manually assign the pins to each serial port in the INO file like this

```C++

...

const int TTY1SerialTX = 15;
const int TTY1SerialRX = 16;

const int TTY2SerialTX = 17;
const int TTY2SerialRX = 18;

void setup(void) {
  pinMode(LED, OUTPUT);
  digitalWrite(LED, LOW);
  Serial.begin(SERIALSPD);
  Serial1.begin(SERIALSPD, SERIAL_8N1, TTY1SerialRX, TTY1SerialTX);
  Serial2.begin(SERIALSPD, SERIAL_8N1, TTY2SerialRX, TTY2SerialTX);

...

```

I have also added a hardware file for my esp32 board

I'm also trying to figure why the boot message goes over the Serial1

Thanks :)

**Comment by MockbaTheBorg** [comment]
We need to evaluate how much of this functionality can be moved to the
hardware definition file (and globals.h) in a way that someone having a
different board would just need to change that file and nothing else, like
we have today.
I want to avoid that someone else, willing to use an additional serial,
would have to go change source inside the RunCPM innards. That would make
it hard to support.
For example: whatever needs to be in RunCPM.ino, for arduinos, wild need to
have an equivalent on main.c, so people on the PCs could also enable the
functionality seamlessly.

**Comment by TurBoss** [comment]
hello, sorry for the delay

I was curious if platformio could be an opition to have many platforms 

```ini
[platformio]

;default_envs = teensy41
default_envs = esp32s3
;default_envs = linux

[env]
framework = arduino

[env:teensy41]
platform = teensy
board = teensy41
board_build.mcu = imxrt1062
board_build.f_cpu = 600000000L
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
upload_protocol = teensy-cli
lib_deps =
	greiman/SdFat@=2.2.3
	
build_flags =
    -DCORE_TEENSY
	-DDISABLE_FS_H_WARNING 
    -DTEENSY_OPT_FAST_LTO
    -DUSB_SERIAL
    -DSPI_DRIVER_SELECT=0
    -DSDFAT_FILE_TYPE=1


[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
monitor_speed = 115200
board_build.flash_mode = dio
lib_deps =
	greiman/SdFat@=2.2.3
;build_flags = -DBOARD_HAS_PSRAM
;board_build.partitions = partitions.csv
;board_build.filesystem = spiffs
build_flags = 
	-DESP32
    -DUSB_SERIAL
	-DDISABLE_FS_H_WARNING 
	-DSPI_DRIVER_SELECT=0
	-DSDFAT_FILE_TYPE=1
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

[env:windows]
platform = windows_x86

[env:linux]
platform = linux_x86_64

[env:linux_arm]
platform = linux_arm
```

thanks

**Comment by MockbaTheBorg** [comment]
Hi there ... I am freezing the code of RunCPM ... from now on no more feature adding to it. (unless someone creates their own fork to work on)
Its been a long journey, more than 10 years, but I am having to change gears away from it.

**Comment by TurBoss** [comment]
cool Thank you!

**Comment by wrljet** [comment]
Thank you for sharing your very neat project.../Bill

**Pull request closed without merging**
