### PR TITLE
Posix console fix

### PR DESCRIPTION
**Pull request by kklis**
MUMPS now works as expected

### CODE REVIEW

**Comment by MockbaTheBorg** [comment]
Whoohoo ... can't wait to test this.

**Comment by MockbaTheBorg** [comment]
It seems to work fine ... awesome!!!
Thanks man!

So, what was the reason at the end?

**Comment by kklis** [comment]
The kbhit() function is non-standard and is not supported on Linux, OS X, BSD, etc. so I used an implementation suggested on different user forums. Unfortunately, this implementation is blocking, while original kbhit() is not.
The second problem was that the output was buffered, which caused prompt in MUMPS not to appear. After I fixed kbhit() you had to press Enter to see the prompt, which was pretty annoying. This one was fixed by setting setvbuf() to 0 on stdout.

**Comment by MockbaTheBorg** [comment]
Awesome!!!

**Pull request merged**
