### PR TITLE
verify RunCPM can be built for every push

### PR DESCRIPTION
**Pull request by ravn**

### CODE REVIEW

**Comment by MockbaTheBorg** [comment]
Hi Ravn,

Sorry I do not know GitHub capabilities in depth.
Can this operation be done for every port, like Arduino, Teensy, Windows, MacOS, etc?   Or is it specific for Linux?
If specific for Linux I prefer not to have it. My plan if to have only things that can be done for all platforms.
I might even remove Lua support in the future, or make it very optional. As it can't be implemented the same way for microprocessors.

Thanks,
Marcelo.

**Comment by MockbaTheBorg** [comment]
Actually ... I like the idea of having it build for Linux, Windows and Mac. Do you know how to make it for all?
I think we should bring it in if we can do for all OSes which require building with a non-arduino based compiler.
This could indeed be an option to have people get built versions without having to compile it themselves.

**Comment by johnsonjh** [comment]
This is a great idea.

While I have zero experience with GitHub Actions, I do a lot of work with GitLab's CI/CD, which includes cross-compiling releases.

For example, we build [DPS8M](https://dps8m.gitlab.io/dps8m/Releases/) releases for *13 operating systems and 23 different architectures*, not including sub-architecture optimized builds, from our CI pipeline.  We are also running a huge battery of tests (which takes several hours) on every single commit, and offering those builds as well, assuming everything passes.

For another project, [libsir](https://github.com/aremmell/libsir), we're using GitLab for [CI/CD](https://gitlab.com/libsir/libsir/pipelines/master/latest), but still primarily hosting development on GitHub.  

You do have to make a distinction between just building releases and actually testing them.  Testing is a bit more difficult since an environment that can build releases (via cross-compilation, etc.) is easier to achieve and maintain than a full environment capable of executing all the builds, but it can still be done (QEMU, Wine, etc.) if you need to.

Hopefully @ravn can get you going with GitHub Actions for builds, but the real "fun" comes up when you start running actual *tests*. :)

**Comment by ravn** [comment]
I added builds for Windows and macOS. 

They just run make, but it is a start 🙂

**Comment by ravn** [comment]
> You do have to make a distinction between just building releases and actually testing them. Testing is a bit more difficult since an environment that can build releases (via cross-compilation, etc.) is easier to achieve and maintain than a full environment capable of executing all the builds, but it can still be done (QEMU, Wine, etc.) if you need to.

A full test suite would be nice, but would require extra work.   I would suggest a low-hanging fruit test suite could be:

* Ensure the emulation is correct by running ZEXEALL - I believe it passes at the moment.
* Do a non-trivial compilation suite, like compiling a CCP replacement using the tools already present in A.ZIP, and comparing the output to a result known to be correct.

I do not know how much can be done on the free plan for Github actions but the above should be doable for pushes to main.

**Comment by MockbaTheBorg** [comment]
Here we go ... lets start a new challenge.

**Pull request merged**
